.\" srcrr
.\" Copyright (c) 2019, Colvin Wellborn
.Dd June 19, 2019
.Dt SRCRR 1
.\" NAME
.Sh NAME
.Nm srcrr
.Nd load a development project shell context
.\" SYNOPSIS
.Sh SYNOPSIS
.Nm
.Op Fl vSUP
.Ar project_name
.Nm
.Fl l
.Nm
.Fl h
.\" DESCRIPTION
.Sh DESCRIPTION
.Nm
searches a set of directories, defined in the
.Ev SRCPATH
environment variable, for a project directory matching the given
.Ar project_name .
Once found, it prints to standard output the shell commands necessary to change
directories to that project and source an optional series of initialization
files if they exist: first, the system-wide file
.Pa /etc/srcrrrc ,
second the user-wide file
.Pa $HOME/.srcrrrc ,
and finally the project-specific file
.Pa .srcrrc
located within the project directory.
.Pp
The shell code emitted by this program can be loaded into the current shell
session using
.Xr eval 1
or similar. A shell function named
.Em src
is typically provided alongside this program to do so automatically.
.Pp
The
.Ev SRCPATH
environment variable is similar to the
.Ev PATH
variable. It consists of a list of one or more directories, each separated by a
single colon character, that are searched in left-to-right order.
.Pp
It is not an error for a non-existent directory to be listed in the
.Ev SRCPATH .
.\" OPTIONS
.Sh OPTIONS
.Bl -tag -compact -offset indent
.It Fl v
print verbose information on standard error
.It Fl l
list all project directories
.It Fl S
ignore the system-wide file
.It Fl U
ignore the user-wide file
.It Fl P
ignore the project file
.It Fl V
report the version and exit
.It Fl h
display this help
.El
.\" ENVIRONMENT
.Sh ENVIRONMENT
.Bl -tag -compact -offset indent -width XXXXXXXXXX
.It SRCPATH
List of directories in which to search for projects.
.El
.\" AUTHORS
.Sh AUTHORS
.Bl -diag -compact
.It Colvin Wellborn colvinwellborn@gmail.com
.El
.\" LICENSE
.Sh LICENSE
This program is provided under the terms of the BSD 2-Clause License.
